#!/usr/bin/env ruby

require 'highline/import'
Dir["./app/**/*.rb"].each {|f| require f}
Dir["./lib/**/*.rb"].each {|f| require f}


def print_error_message
  puts "[Help] Run as: ./mood_music manage"
end


if ARGV.size == 1 and ARGV[0] == 'manage'
  recommendations_controller= RecommendationsController.new
  recommendations_controller.list_main_menu
elsif ARGV.size == 1 and ARGV[0] == 'recommend'
  puts "What is your mood today?"
  choose do |menu|
    menu.prompt = ""
    recommendations_controller= RecommendationsController.new
    menu.choice('happy') do
      puts recommendations_controller.find_recommendation('happy')
    end
    menu.choice('sad') do
      puts recommendations_controller.find_recommendation('sad')
    end
    menu.choice('mellow') do
      puts recommendations_controller.find_recommendation('mellow')
    end
    menu.choice('angry') do
      puts recommendations_controller.find_recommendation('angry')
    end
  end
else
  print_error_message
end
